### ISSUE TITLE
Option to change perspectiveViewBackgroundColor in EasyViewer

### ISSUE THREAD

**Issue by tony-azevedo** [seung-lab/NeuroglancerAnnotationUI#21]
Many people find it useful to have a white background in neuroglancer. Thus, it would be nice to be able to do this from the statebuilder as well by setting the s.perspectiveViewBackgroundColor=[input color, e.g. #ffffff].  I think the relevant code is in [EasyViewerSub.set_view_options()](https://github.com/seung-lab/NeuroglancerAnnotationUI/blob/6fd9deb629951dc3f5d5bfacfde4c41959546715/src/nglui/easyviewer/base.py#L341)

`with self.txn() as s:
                if show_slices is not None:
                    s.showSlices = show_slices
                if layout is not None:
                    s.layout.type = layout
                if show_axis_lines is not None:
                    s.show_axis_lines = show_axis_lines
                if show_scale_bar is not None:
                    s.show_scale_bar = show_scale_bar
                if orthographic is not None:
                    s.layout.orthographic_projection = orthographic
                if position is not None:
                    if compatibility_mode:
                        s.position = position
                    else:
                        s.position.voxelCoordinates = position
                if zoom_image is not None:
                    if compatibility_mode:
                        s.cross_section_scale = zoom_image
                    else:
                        s.navigation.zoomFactor = zoom_image
                if zoom_3d is not None:
                    if compatibility_mode:
                        s.projectionScale = zoom_3d
                    else:
                        s.perspectiveZoom = zoom_3d`

**Comment by ceesem** [comment]
Added in #24
