### ISSUE TITLE
ChainedStateBuilder.render_state() takes a dict as input indicating the assignment of synapse dfs to layers.

### ISSUE THREAD

**Issue by tony-azevedo** [seung-lab/NeuroglancerAnnotationUI#22]
@ceesem and I discussed this syntax, just posting here to keep track of the idea.

E.g.

`glu_layer = ngstbld.AnnotationLayerConfig(name='Glu',
                                       mapping_rules=glu_points,
                                       linked_segmentation_layer=seg_layer.name,
                                       color='#FEDF08',
                                       data_group = 'glu'     )

sb = ngstbld.StateBuilder(layers=[gaba_layer,glu_layer],client=client)

sb.render_state({'glu": glu_df, "gaba": gaba_df})`

**Comment by ceesem** [comment]
Added in #24
